variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "private_key_password" {}
variable "app_tag" {}
variable "environment" {}
variable "home_region" {}
variable "region" {}
variable "vcn_name" {}
variable "vcn_dns_label" {}
variable "vcn_cidr" {}
variable "compartment_ocid" {}